# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.srcs/sources_1/bd/dmaSystem/ip/dmaSystem_auto_us_1/dmaSystem_auto_us_1.xci
# IP: The module: 'dmaSystem_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_auto_us_1/dmaSystem_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaSystem_auto_us_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_auto_us_1/dmaSystem_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaSystem_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.srcs/sources_1/bd/dmaSystem/ip/dmaSystem_auto_us_1/dmaSystem_auto_us_1.xci
# IP: The module: 'dmaSystem_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_auto_us_1/dmaSystem_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaSystem_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_auto_us_1/dmaSystem_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaSystem_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
