# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/twipaa/Downloads/new_fpga/new_fpga.srcs/sources_1/ip/mem_wrapper/mem_wrapper.xci
# IP: The module: 'mem_wrapper' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/twipaa/Downloads/new_fpga/new_fpga.gen/sources_1/ip/mem_wrapper/mem_wrapper_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_wrapper'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/twipaa/Downloads/new_fpga/new_fpga.srcs/sources_1/ip/mem_wrapper/mem_wrapper.xci
# IP: The module: 'mem_wrapper' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/twipaa/Downloads/new_fpga/new_fpga.gen/sources_1/ip/mem_wrapper/mem_wrapper_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_wrapper'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
