# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.srcs/sources_1/ip/extern_bram/extern_bram.xci
# IP: The module: 'extern_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.gen/sources_1/ip/extern_bram/extern_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'extern_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.srcs/sources_1/ip/extern_bram/extern_bram.xci
# IP: The module: 'extern_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.gen/sources_1/ip/extern_bram/extern_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'extern_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
