# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.runs/synth_1/tpu.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 14
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.cache/wt [current_project]
set_property parent.project_path /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/iram_mem.coe
add_files /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/imem_ram.coe
add_files /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/external_bram.coe
read_verilog /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/define.vh
set_property is_global_include true [get_files /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/define.vh]
read_verilog -library xil_defaultlib {
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/DFFE.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/DFFR.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/DFFRE.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/DFFSE.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/acc.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/act_mod.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/alu.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/axi_read_intf.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/axi_write_intf.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/data_byte_shift.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/dec32to5.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/dec4to16.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/dec5to32.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/dec8to4.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/idu.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/ifu.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lsu.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/mem_wrapper/mem_wrapper.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/mm_ctrl_buffer.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/mux16.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/mxu.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/mxu8.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/pe.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/mem_wrapper/ram_mem_wrapper.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/resp_assign.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/lib/resp_data_get.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/rf.v
  /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/rtl/tpu.v
}
read_ip -quiet /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.srcs/sources_1/ip/fpga_mem_wrapper/fpga_mem_wrapper.xci
set_property used_in_implementation false [get_files -all /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.gen/sources_1/ip/fpga_mem_wrapper/fpga_mem_wrapper_ooc.xdc]

read_ip -quiet /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.srcs/sources_1/ip/fpga_ram_mem_wrapper/fpga_ram_mem_wrapper.xci
set_property used_in_implementation false [get_files -all /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.gen/sources_1/ip/fpga_ram_mem_wrapper/fpga_ram_mem_wrapper_ooc.xdc]

read_ip -quiet /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.srcs/sources_1/ip/extern_bram/extern_bram.xci
set_property used_in_implementation false [get_files -all /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.gen/sources_1/ip/extern_bram/extern_bram_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.srcs/constrs_1/new/tpu.xdc
set_property used_in_implementation false [get_files /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.srcs/constrs_1/new/tpu.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /dfs/usrhome/twipaa/Documents/big_ram/ZW02a-25_FYP_repo/FPGA/FPGA.srcs/utils_1/imports/synth_1/tpu.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top tpu -part xc7z020clg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef tpu.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file tpu_utilization_synth.rpt -pb tpu_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
