# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.srcs/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/dmaSystem_system_ila_0_0.xci
# IP: The module: 'dmaSystem_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/bd_dfc6.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6 || ORIG_REF_NAME==bd_dfc6} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_0/bd_dfc6_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_ila_lib_0 || ORIG_REF_NAME==bd_dfc6_ila_lib_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_1/bd_dfc6_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_g_inst_0 || ORIG_REF_NAME==bd_dfc6_g_inst_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_2/bd_dfc6_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_0_aw_0 || ORIG_REF_NAME==bd_dfc6_slot_0_aw_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_3/bd_dfc6_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_0_w_0 || ORIG_REF_NAME==bd_dfc6_slot_0_w_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_4/bd_dfc6_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_0_b_0 || ORIG_REF_NAME==bd_dfc6_slot_0_b_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_5/bd_dfc6_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_0_ar_0 || ORIG_REF_NAME==bd_dfc6_slot_0_ar_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_6/bd_dfc6_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_0_r_0 || ORIG_REF_NAME==bd_dfc6_slot_0_r_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_7/bd_dfc6_slot_1_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_1_aw_0 || ORIG_REF_NAME==bd_dfc6_slot_1_aw_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_8/bd_dfc6_slot_1_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_1_w_0 || ORIG_REF_NAME==bd_dfc6_slot_1_w_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_9/bd_dfc6_slot_1_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_1_b_0 || ORIG_REF_NAME==bd_dfc6_slot_1_b_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_10/bd_dfc6_slot_1_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_1_ar_0 || ORIG_REF_NAME==bd_dfc6_slot_1_ar_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_11/bd_dfc6_slot_1_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_1_r_0 || ORIG_REF_NAME==bd_dfc6_slot_1_r_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_12/bd_dfc6_slot_2_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_2_aw_0 || ORIG_REF_NAME==bd_dfc6_slot_2_aw_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_13/bd_dfc6_slot_2_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_2_w_0 || ORIG_REF_NAME==bd_dfc6_slot_2_w_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_14/bd_dfc6_slot_2_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_2_b_0 || ORIG_REF_NAME==bd_dfc6_slot_2_b_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_15/bd_dfc6_slot_2_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_2_ar_0 || ORIG_REF_NAME==bd_dfc6_slot_2_ar_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_16/bd_dfc6_slot_2_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_2_r_0 || ORIG_REF_NAME==bd_dfc6_slot_2_r_0} -quiet] -quiet

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_dfc6_ila_lib_0 || ORIG_REF_NAME==bd_dfc6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_dfc6_ila_lib_0 || ORIG_REF_NAME==bd_dfc6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_0/bd_dfc6_ila_lib_0_ooc.xdc

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/bd_dfc6_ooc.xdc

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/dmaSystem_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaSystem_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.srcs/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/dmaSystem_system_ila_0_0.xci
# IP: The module: 'dmaSystem_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/bd_dfc6.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6 || ORIG_REF_NAME==bd_dfc6} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_0/bd_dfc6_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_ila_lib_0 || ORIG_REF_NAME==bd_dfc6_ila_lib_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_1/bd_dfc6_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_g_inst_0 || ORIG_REF_NAME==bd_dfc6_g_inst_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_2/bd_dfc6_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_0_aw_0 || ORIG_REF_NAME==bd_dfc6_slot_0_aw_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_3/bd_dfc6_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_0_w_0 || ORIG_REF_NAME==bd_dfc6_slot_0_w_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_4/bd_dfc6_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_0_b_0 || ORIG_REF_NAME==bd_dfc6_slot_0_b_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_5/bd_dfc6_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_0_ar_0 || ORIG_REF_NAME==bd_dfc6_slot_0_ar_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_6/bd_dfc6_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_0_r_0 || ORIG_REF_NAME==bd_dfc6_slot_0_r_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_7/bd_dfc6_slot_1_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_1_aw_0 || ORIG_REF_NAME==bd_dfc6_slot_1_aw_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_8/bd_dfc6_slot_1_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_1_w_0 || ORIG_REF_NAME==bd_dfc6_slot_1_w_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_9/bd_dfc6_slot_1_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_1_b_0 || ORIG_REF_NAME==bd_dfc6_slot_1_b_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_10/bd_dfc6_slot_1_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_1_ar_0 || ORIG_REF_NAME==bd_dfc6_slot_1_ar_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_11/bd_dfc6_slot_1_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_1_r_0 || ORIG_REF_NAME==bd_dfc6_slot_1_r_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_12/bd_dfc6_slot_2_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_2_aw_0 || ORIG_REF_NAME==bd_dfc6_slot_2_aw_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_13/bd_dfc6_slot_2_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_2_w_0 || ORIG_REF_NAME==bd_dfc6_slot_2_w_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_14/bd_dfc6_slot_2_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_2_b_0 || ORIG_REF_NAME==bd_dfc6_slot_2_b_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_15/bd_dfc6_slot_2_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_2_ar_0 || ORIG_REF_NAME==bd_dfc6_slot_2_ar_0} -quiet] -quiet

# IP: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_16/bd_dfc6_slot_2_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfc6_slot_2_r_0 || ORIG_REF_NAME==bd_dfc6_slot_2_r_0} -quiet] -quiet

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_dfc6_ila_lib_0 || ORIG_REF_NAME==bd_dfc6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_dfc6_ila_lib_0 || ORIG_REF_NAME==bd_dfc6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/ip/ip_0/bd_dfc6_ila_lib_0_ooc.xdc

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/bd_0/bd_dfc6_ooc.xdc

# XDC: /dfs/usrhome/twipaa/Documents/uart/ZW02a-25_FYP_repo/DMA_SAMPLE/DMA_SYSTEM/DMA_SYSTEM.gen/sources_1/bd/dmaSystem/ip/dmaSystem_system_ila_0_0/dmaSystem_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmaSystem_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
